# Generated by Django 5.1.15 on 2026-07-20 01:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("excerpt", models.TextField()),
                ("content", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="blog/")),
                ("author_name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("read_time", models.CharField(max_length=20)),
                ("is_published", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
