# Generated by Django 5.1.15 on 2026-08-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_onetimecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data da eliminação suave (soft-delete). Distingue conta eliminada de conta bloqueada.",
                null=True,
            ),
        ),
    ]
