# Generated by Django 5.1.15 on 2026-07-27 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_returnrequest"),
        ("stores", "0006_store_product_type_alter_store_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="store_name",
            field=models.CharField(
                blank=True,
                help_text="Nome da loja no momento do pedido (preservado se loja for eliminada)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="stores.store",
            ),
        ),
    ]
