# Generated by Django 5.1.15 on 2026-08-11 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_store_name_alter_order_store"),
        ("stores", "0011_storefollower"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="returns/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name": "Imagem da Devolução",
                "verbose_name_plural": "Imagens das Devoluções",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="buyer_tracking_code",
            field=models.CharField(
                blank=True,
                help_text="Código de rastreio da devolução (preenchido pelo comprador)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="reason_type",
            field=models.CharField(
                choices=[
                    ("defective", "Produto com defeito"),
                    ("not_as_described", "Produto diferente do anunciado"),
                    ("not_satisfied", "Não serviu / Não gostei"),
                    ("damaged", "Embalagem danificada"),
                    ("wrong_item", "Item errado enviado"),
                    ("other", "Outro"),
                ],
                default="other",
                help_text="Tipo de motivo da devolução",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="return_address",
            field=models.TextField(
                blank=True,
                help_text="Morada para onde o comprador deve enviar a devolução",
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="return_instructions",
            field=models.TextField(
                blank=True,
                help_text="Instruções de devolução para o comprador (morada, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="rma_number",
            field=models.CharField(
                blank=True,
                help_text="Número único de autorização (ex: RMA-2026-001)",
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="vendor_notes",
            field=models.TextField(
                blank=True,
                help_text="Notas do vendedor (instruções de devolução, etc.)",
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["store", "status"], name="orders_retu_store_i_401c0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["buyer", "status"], name="orders_retu_buyer_i_a8057a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["rma_number"], name="orders_retu_rma_num_de8dc0_idx"
            ),
        ),
        migrations.AddField(
            model_name="returnimage",
            name="return_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="orders.returnrequest",
            ),
        ),
    ]
