# Generated by Django 5.1.15 on 2026-08-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_returnimage_returnrequest_buyer_tracking_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnrequest",
            name="shipping_notes",
            field=models.TextField(
                blank=True,
                help_text="Descrição de como o comprador enviou a devolução (ex: transportadora, contacto)",
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="buyer_tracking_code",
            field=models.CharField(
                blank=True,
                help_text="Código de rastreio ou referência da devolução (opcional)",
                max_length=100,
            ),
        ),
    ]
