# Generated by Django 5.1.15 on 2026-08-11 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_returnrequest_shipping_notes_and_more"),
        ("stores", "0011_storefollower"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="returnrequest",
            name="admin_notes",
            field=models.TextField(
                blank=True,
                help_text="Notas internas do admin (não visíveis para comprador/vendedor)",
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="disputed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data em que o comprador escalou para o admin",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin que reviu/interveio nesta devolução",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_returns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Solicitada"),
                    ("approved", "Aprovada"),
                    ("rejected", "Rejeitada"),
                    ("disputed", "Em Disputa"),
                    ("shipped", "Devolução Enviada"),
                    ("received", "Recebida"),
                    ("refunded", "Reembolsada"),
                ],
                default="requested",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["status", "disputed_at"], name="orders_retu_status_717798_idx"
            ),
        ),
    ]
