# Generated by Django 5.1.15 on 2026-08-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_returnrequest_admin_notes_returnrequest_disputed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data em que o comprador confirmou a receção",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data em que o vendedor marcou como enviado",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_evidence",
            field=models.ImageField(
                blank=True,
                help_text="Foto do pacote/envio como prova",
                upload_to="orders/evidence/",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_notes",
            field=models.TextField(
                blank=True,
                help_text='Descrição de como/quem entregou (ex: "motorista João, tel 84xxx")',
            ),
        ),
    ]
