# Generated by Django 5.1.15 on 2026-08-12 00:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_order_confirmed_at_order_shipped_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("confirmed", "Confirmada"),
                            ("processing", "Em Processamento"),
                            ("shipped", "Enviada"),
                            ("delivered", "Entregue"),
                            ("cancelled", "Cancelada"),
                            ("refunded", "Reembolsada"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("confirmed", "Confirmada"),
                            ("processing", "Em Processamento"),
                            ("shipped", "Enviada"),
                            ("delivered", "Entregue"),
                            ("cancelled", "Cancelada"),
                            ("refunded", "Reembolsada"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, help_text="Motivo/nota da mudança", max_length=500
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Order status histories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "-created_at"],
                        name="orders_orde_order_i_ca028d_idx",
                    )
                ],
            },
        ),
    ]
