# Generated by Django 5.1.15 on 2026-08-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_supportticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_pickup",
            field=models.BooleanField(
                default=False,
                help_text="Se a encomenda usa levantamento na loja em vez de entrega",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("confirmed", "Confirmada"),
                    ("processing", "Em Processamento"),
                    ("shipped", "Enviada"),
                    ("ready_for_pickup", "Pronto para Levantamento"),
                    ("delivered", "Entregue"),
                    ("cancelled", "Cancelada"),
                    ("refunded", "Reembolsada"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("confirmed", "Confirmada"),
                    ("processing", "Em Processamento"),
                    ("shipped", "Enviada"),
                    ("ready_for_pickup", "Pronto para Levantamento"),
                    ("delivered", "Entregue"),
                    ("cancelled", "Cancelada"),
                    ("refunded", "Reembolsada"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="previous_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("confirmed", "Confirmada"),
                    ("processing", "Em Processamento"),
                    ("shipped", "Enviada"),
                    ("ready_for_pickup", "Pronto para Levantamento"),
                    ("delivered", "Entregue"),
                    ("cancelled", "Cancelada"),
                    ("refunded", "Reembolsada"),
                ],
                max_length=20,
            ),
        ),
    ]
