# Generated by Django 5.1.15 on 2026-08-12 21:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_order_is_pickup_alter_order_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTicketImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="tickets/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=300)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="orders.supportticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem do Ticket",
                "verbose_name_plural": "Imagens dos Tickets",
                "ordering": ["created_at"],
            },
        ),
    ]
