# Generated by Django 5.1.15 on 2026-08-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0012_supportticketimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
