# Generated by Django 5.1.15 on 2026-08-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0014_abandonedcart"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tipo do produto no momento do pedido (physical/digital/course)",
                max_length=20,
            ),
        ),
    ]
