# Generated by Django 5.1.15 on 2026-08-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliatecommission",
            name="rejection_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="affiliateprofile",
            name="commission_tier",
            field=models.CharField(
                choices=[("basic", "Básico"), ("silver", "Prata"), ("gold", "Ouro")],
                default="basic",
                max_length=20,
            ),
        ),
    ]
