# Generated by Django 5.1.15 on 2026-08-12 23:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0005_affiliatecommission_rejection_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliateSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cookie_window_days", models.PositiveIntegerField(default=30)),
                (
                    "default_commission_rate",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                (
                    "min_payout_amount",
                    models.DecimalField(decimal_places=2, default=500, max_digits=12),
                ),
                ("approve_after_days", models.PositiveIntegerField(default=7)),
            ],
            options={
                "verbose_name": "Configuração de Afiliados",
                "verbose_name_plural": "Configurações de Afiliados",
            },
        ),
        migrations.AddField(
            model_name="affiliateprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("active", "Activo"),
                    ("suspended", "Suspenso"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="affiliateprofile",
            name="total_withdrawn",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="AffiliatePayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("mpesa", "M-Pesa"),
                            ("emola", "e-Mola"),
                            ("bank", "Transferência Bancária"),
                        ],
                        default="mpesa",
                        max_length=20,
                    ),
                ),
                ("account_details", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("paid", "Pago"),
                            ("rejected", "Rejeitado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="affiliates.affiliateprofile",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
