# Generated by Django 5.1.15 on 2026-08-13 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0006_affiliatesettings_affiliateprofile_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliatesettings",
            name="clawback_days",
            field=models.PositiveIntegerField(
                default=30, help_text="Dias para reverter comissões após aprovação"
            ),
        ),
        migrations.AddField(
            model_name="affiliatesettings",
            name="payout_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Taxa da plataforma sobre cada saque (%)",
                max_digits=5,
            ),
        ),
        migrations.CreateModel(
            name="AffiliateKYC",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("bi", "Bilhete de Identidade"),
                            ("passport", "Passaporte"),
                        ],
                        default="bi",
                        max_length=20,
                    ),
                ),
                ("document_number", models.CharField(max_length=100)),
                ("nuit", models.CharField(blank=True, max_length=50)),
                ("payout_phone", models.CharField(max_length=30)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_account", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                (
                    "affiliate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc",
                        to="affiliates.affiliateprofile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_kycs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
