# Generated by Django 5.1.15 on 2026-08-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0007_affiliatesettings_clawback_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliatesettings",
            name="affiliate_program_active",
            field=models.BooleanField(
                default=True, help_text="Interruptor geral do programa de afiliados"
            ),
        ),
        migrations.AddField(
            model_name="affiliatesettings",
            name="max_commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="Percentagem máxima permitida por produto",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="affiliatesettings",
            name="min_commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Percentagem mínima permitida por produto",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="affiliatesettings",
            name="terms_of_service",
            field=models.TextField(
                blank=True,
                help_text="Termos globais do programa exibidos na Área de Afiliação",
            ),
        ),
    ]
