# Generated by Django 5.1.15 on 2026-08-13 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="payout_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Saldo virtual disponível para saque (vendedor/afiliado)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Saldo comprável (buyer)",
                max_digits=12,
            ),
        ),
        migrations.CreateModel(
            name="WalletEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("debit", "Débito"), ("credit", "Crédito")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("buyer", "Saldo comprável"),
                            ("payout", "Saldo para saque"),
                            ("platform", "Plataforma"),
                        ],
                        default="buyer",
                        max_length=20,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="wallet.wallettransaction",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "-created_at"],
                        name="wallet_wall_wallet__006c46_idx",
                    )
                ],
            },
        ),
    ]
