# Generated by Django 5.1.15 on 2026-08-13 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0003_escrowholding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="reserved_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Valor reservado em pedidos de saque pendentes/aprovados",
                max_digits=12,
            ),
        ),
        migrations.CreateModel(
            name="PayoutRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("seller", "Vendedor"), ("affiliate", "Afiliado")],
                        default="seller",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("mpesa", "M-Pesa"),
                            ("emola", "e-Mola"),
                            ("bank", "Transferência Bancária"),
                        ],
                        default="mpesa",
                        max_length=20,
                    ),
                ),
                ("account_details", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("paid", "Pago"),
                            ("rejected", "Rejeitado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_reference",
                    models.CharField(
                        blank=True,
                        help_text="Referência/confirmação do pagamento manual",
                        max_length=255,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_approved_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_paid_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
