# Generated by Django 5.1.15 on 2026-08-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courselesson",
            name="duration",
        ),
        migrations.AddField(
            model_name="courselesson",
            name="cloudflare_video_status",
            field=models.CharField(
                choices=[
                    ("pending", "Aguardando Upload"),
                    ("uploading", "A Enviar"),
                    ("processing", "A Processar"),
                    ("ready", "Pronto"),
                    ("error", "Erro"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="cloudflare_video_uid",
            field=models.CharField(
                blank=True,
                help_text="UID do video no Cloudflare Stream",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="video_duration_seconds",
            field=models.PositiveIntegerField(
                default=0, help_text="Duracao em segundos"
            ),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="video_thumbnail",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="watched_duration",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="courselesson",
            name="video_provider",
            field=models.CharField(
                choices=[
                    ("cloudflare", "Cloudflare Stream"),
                    ("vimeo", "Vimeo"),
                    ("youtube", "YouTube"),
                ],
                default="cloudflare",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="courselesson",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="URL publica do video (legado: Vimeo/YouTube)"
            ),
        ),
    ]
