# Generated by Django 5.1.15 on 2026-08-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_remove_courselesson_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="access_duration_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Dias de acesso apos matricula. Null = acesso vitalicio.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="access_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data de expiracao do acesso. Null = vitalicio.",
                null=True,
            ),
        ),
    ]
