# Generated by Django 5.1.15 on 2026-08-10 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0006_question_answeroption_quiz_question_quiz_quizattempt_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="Avaliação de 1 a 5 estrelas."
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Título da review.", max_length=255
                    ),
                ),
                ("body", models.TextField(help_text="Comentário da review.")),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Se False, visível apenas para o autor."
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False, help_text="Indica se a review foi editada."
                    ),
                ),
                (
                    "seller_reply",
                    models.TextField(blank=True, help_text="Resposta do instrutor."),
                ),
                ("seller_replied_at", models.DateTimeField(blank=True, null=True)),
                ("report_count", models.PositiveIntegerField(default=0)),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False, help_text="Ocultado por moderação."
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Curso avaliado (denormalizado para queries mais rápidas).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="courses.course",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        help_text="Matrícula do aluno que fez a review.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="courses.enrollment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["course", "-created_at"],
                        name="courses_cou_course__845eb3_idx",
                    ),
                    models.Index(
                        fields=["enrollment"], name="courses_cou_enrollm_a7cb52_idx"
                    ),
                ],
            },
        ),
    ]
