# Generated by Django 5.1.15 on 2026-08-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_coursereview"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursemodule",
            name="drip_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Dias após matrícula para desbloquear este módulo. Null = imediato.",
                null=True,
            ),
        ),
    ]
