# Generated by Django 5.1.15 on 2026-08-11 07:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0011_storefollower"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Nome do método (ex: "Standard", "Expresso")',
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descrição visível para o cliente"
                    ),
                ),
                (
                    "estimated_days_min",
                    models.PositiveIntegerField(
                        default=1, help_text="Prazo mínimo em dias"
                    ),
                ),
                (
                    "estimated_days_max",
                    models.PositiveIntegerField(
                        default=7, help_text="Prazo máximo em dias"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_methods",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Método de Envio",
                "verbose_name_plural": "Métodos de Envio",
                "ordering": ["name"],
                "unique_together": {("store", "name")},
            },
        ),
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Nome da zona (ex: "Maputo Cidade", "Zona Sul")',
                        max_length=255,
                    ),
                ),
                (
                    "provinces",
                    models.JSONField(
                        default=list,
                        help_text='Lista de províncias cobertas. Ex: ["maputo_cidade", "maputo_provincia"]',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_zones",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zona de Entrega",
                "verbose_name_plural": "Zonas de Entrega",
                "ordering": ["name"],
                "unique_together": {("store", "name")},
            },
        ),
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Preço base em MZN (independente do peso)",
                        max_digits=10,
                    ),
                ),
                (
                    "per_kg_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Preço adicional por kg em MZN (0 = preço fixo)",
                        max_digits=10,
                    ),
                ),
                (
                    "free_shipping_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor mínimo do pedido para frete grátis. Null = nunca grátis.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "max_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso máximo em kg. Null = sem limite.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="shipping.shippingmethod",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="shipping.shippingzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa de Envio",
                "verbose_name_plural": "Tarifas de Envio",
                "ordering": ["base_price"],
            },
        ),
    ]
