# Generated by Django 5.1.15 on 2026-08-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingmethod",
            name="method_type",
            field=models.CharField(
                choices=[
                    ("delivery", "Entrega ao Domicílio"),
                    ("pickup", "Levantamento em Loja"),
                ],
                default="delivery",
                help_text="Tipo: entrega ou levantamento",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="pickup_address",
            field=models.TextField(
                blank=True, help_text="Morada de levantamento (se method_type=pickup)"
            ),
        ),
    ]
