# Generated by Django 5.1.15 on 2026-08-21 11:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0002_shippingmethod_method_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fallback_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Aplicar frete de fallback quando a loja não configurou envio",
                    ),
                ),
                (
                    "fallback_label",
                    models.CharField(
                        default="Envio Padrão (Plataforma)",
                        help_text="Nome do método de envio exibido ao comprador",
                        max_length=100,
                    ),
                ),
                (
                    "fallback_days_min",
                    models.PositiveIntegerField(
                        default=3, help_text="Prazo mínimo estimado (dias)"
                    ),
                ),
                (
                    "fallback_days_max",
                    models.PositiveIntegerField(
                        default=10, help_text="Prazo máximo estimado (dias)"
                    ),
                ),
                (
                    "default_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=350.0,
                        help_text="Taxa fixa (MZN) usada quando a província não está em province_rates",
                        max_digits=10,
                    ),
                ),
                (
                    "province_rates",
                    models.JSONField(
                        default=dict,
                        help_text='Taxa fixa por província (MZN). Ex: {"maputo_cidade": 300, "maputo_provincia": 350, "nampula": 600}',
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Frete",
                "verbose_name_plural": "Configurações de Frete",
            },
        ),
    ]
