# Generated by Django 5.1.15 on 2026-08-10 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_review_is_hidden_review_report_count_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="storereview",
            unique_together=set(),
        ),
    ]
