# Generated by Django 5.1.15 on 2026-07-20 01:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("about", models.TextField(blank=True)),
                ("logo", models.ImageField(blank=True, upload_to="stores/logos/")),
                ("banner", models.ImageField(blank=True, upload_to="stores/banners/")),
                ("category", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("location", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("active", "Activa"),
                            ("suspended", "Suspensa"),
                            ("closed", "Fechada"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_sales", models.PositiveIntegerField(default=0)),
                ("total_products", models.PositiveIntegerField(default=0)),
                (
                    "default_affiliate_commission",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                ("shipping_policy", models.TextField(blank=True)),
                ("return_policy", models.TextField(blank=True)),
            ],
        ),
    ]
