# Generated by Django 5.1.15 on 2026-07-20 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["status"], name="stores_stor_status_d56e36_idx"),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["slug"], name="stores_stor_slug_e2ab60_idx"),
        ),
    ]
