# Generated by Django 5.1.15 on 2026-07-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("active", "Activa"),
                    ("rejected", "Rejeitada"),
                    ("suspended", "Suspensa"),
                    ("closed", "Fechada"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
