# Generated by Django 5.1.15 on 2026-07-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0003_alter_store_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="tagline",
            field=models.CharField(
                blank=True, help_text="Slogan curto da loja", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="theme_color",
            field=models.CharField(
                blank=True,
                default="#2563eb",
                help_text="Cor hexadecimal (ex: #2563eb)",
                max_length=7,
            ),
        ),
    ]
