# Generated by Django 5.1.15 on 2026-07-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0004_store_tagline_store_theme_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(
                default=5, help_text="Alertar quando stock <= este valor"
            ),
        ),
    ]
