# Generated by Django 5.1.15 on 2026-07-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0005_store_low_stock_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("physical", "Produtos Físicos"),
                    ("digital", "Produtos Digitais"),
                    ("course", "Cursos"),
                ],
                default="physical",
                help_text="Tipo de produto que esta loja vende",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
