# Generated by Django 5.1.15 on 2026-07-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0006_store_product_type_alter_store_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="address_proof",
            field=models.FileField(
                blank=True,
                help_text="Factura de serviço ou comprovativo de morada",
                upload_to="stores/verification/address/",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="admin_notes",
            field=models.TextField(
                blank=True,
                help_text="Notas internas visíveis apenas para administradores",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="identity_document",
            field=models.FileField(
                blank=True,
                help_text="BI, passaporte ou documento de identificação",
                upload_to="stores/verification/identity/",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="tax_document",
            field=models.FileField(
                blank=True,
                help_text="NUIT, licença ou comprovativo fiscal",
                upload_to="stores/verification/tax/",
            ),
        ),
    ]
