# Generated by Django 5.1.15 on 2026-07-31 22:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0007_store_address_proof_store_admin_notes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="Motivo da rejeição (preenchido pelo admin)"
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="address_proof",
            field=models.FileField(
                blank=True,
                help_text="Comprovativo de morada",
                upload_to="stores/documents/address/",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="identity_document",
            field=models.FileField(
                blank=True,
                help_text="Documento de identidade (BI/passaporte)",
                upload_to="stores/documents/identity/",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="tax_document",
            field=models.FileField(
                blank=True,
                help_text="Comprovativo fiscal (NUIT/licença)",
                upload_to="stores/documents/tax/",
            ),
        ),
        migrations.CreateModel(
            name="StoreModerationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approved", "Aprovada"),
                            ("rejected", "Rejeitada"),
                            ("suspended", "Suspensa"),
                            ("reactivated", "Reactivada"),
                            ("closed", "Fechada"),
                            ("edited", "Editada"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Motivo da acção (obrigatório para rejeição)",
                    ),
                ),
                ("previous_status", models.CharField(blank=True, max_length=20)),
                ("new_status", models.CharField(blank=True, max_length=20)),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_logs",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["store", "-created_at"],
                        name="stores_stor_store_i_6a142d_idx",
                    )
                ],
            },
        ),
    ]
