# Generated by Django 5.1.15 on 2026-07-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0008_store_rejection_reason_alter_store_address_proof_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="additional_documents",
            field=models.FileField(
                blank=True,
                help_text="Documentos adicionais (contrato social, etc.)",
                upload_to="stores/documents/additional/",
            ),
        ),
    ]
