# Generated by Django 5.1.15 on 2026-07-26 10:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(blank=True, max_length=100)),
                (
                    "name",
                    models.CharField(
                        help_text='Ex: "Azul / M" ou "Vermelho"', max_length=255
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Preço específico da variante. Se vazio, usa o preço base do produto.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="products/variants/"),
                ),
                (
                    "attributes",
                    models.JSONField(
                        default=dict, help_text='{"Cor": "Azul", "Tamanho": "M"}'
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["product", "is_active"],
                        name="products_pr_product_66459e_idx",
                    ),
                    models.Index(fields=["sku"], name="products_pr_sku_dcab68_idx"),
                ],
                "unique_together": {("product", "sku")},
            },
        ),
    ]
