# Generated by Django 5.1.15 on 2026-07-26 10:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_productvariant"),
        ("stores", "0005_store_low_stock_threshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentagem (%)"),
                            ("fixed", "Valor Fixo (MZN)"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "min_purchase",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(default=0, help_text="0 = ilimitado"),
                ),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("max_per_user", models.PositiveIntegerField(default=1)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Restringir a uma categoria",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Restringir a um produto específico",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["code"], name="products_co_code_814e9d_idx"),
                    models.Index(
                        fields=["store", "is_active"],
                        name="products_co_store_i_a40a48_idx",
                    ),
                ],
            },
        ),
    ]
