# Generated by Django 5.1.15 on 2026-07-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("physical", "Produtos Físicos"),
                    ("digital", "Produtos Digitais"),
                    ("course", "Cursos"),
                ],
                default="physical",
                help_text="Filtrar categorias por tipo de produto",
                max_length=20,
            ),
        ),
    ]
