# Generated by Django 5.1.15 on 2026-07-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_category_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="allow_backorder",
            field=models.BooleanField(
                default=False, help_text="Permitir venda sem stock"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True, help_text="GTIN, EAN, UPC ou ISBN", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(
                blank=True, help_text="Marca ou fabricante", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[
                    ("new", "Novo"),
                    ("used", "Usado"),
                    ("refurbished", "Recondicionado"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Altura em cm",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Comprimento em cm",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Descrição SEO (usa descrição se vazio)",
                max_length=320,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title",
            field=models.CharField(
                blank=True, help_text="Título SEO (usa nome se vazio)", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="min_order_quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="Quantidade mínima por encomenda"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="video_url",
            field=models.URLField(blank=True, help_text="YouTube ou Vimeo"),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_days",
            field=models.PositiveIntegerField(
                default=0, help_text="Dias de garantia (0 = sem garantia)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Peso em kg",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Largura em cm",
                max_digits=7,
                null=True,
            ),
        ),
    ]
