# Generated by Django 5.1.15 on 2026-07-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_product_allow_backorder_product_barcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="Descrição curta para cards/listagens",
                max_length=300,
            ),
        ),
    ]
