# Generated by Django 5.1.15 on 2026-07-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_product_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=500),
        ),
    ]
