# Generated by Django 5.1.15 on 2026-07-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_alter_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="digital_compatibility",
            field=models.CharField(
                blank=True, help_text="Requisitos de sistema/software", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="digital_format",
            field=models.CharField(
                blank=True, help_text="Formato: PDF, ZIP, MP3, MP4, etc.", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="digital_license",
            field=models.CharField(
                choices=[
                    ("personal", "Pessoal"),
                    ("commercial", "Comercial"),
                    ("extended", "Extended"),
                ],
                default="personal",
                help_text="Tipo de licença",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="digital_version",
            field=models.CharField(
                blank=True,
                help_text="Versão do produto digital (ex: v1.0)",
                max_length=50,
            ),
        ),
    ]
