# Generated by Django 5.1.15 on 2026-08-10 21:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_digitaldownload"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "file_size_bytes",
                    models.PositiveIntegerField(
                        default=0, help_text="Tamanho do ficheiro em bytes"
                    ),
                ),
                (
                    "download",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="products.digitaldownload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registo de Download",
                "verbose_name_plural": "Registos de Downloads",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["download", "-created_at"],
                        name="products_do_downloa_8f51ee_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-created_at"],
                        name="products_do_ip_addr_021d84_idx",
                    ),
                ],
            },
        ),
    ]
