# Generated by Django 5.1.15 on 2026-08-11 12:16

import apps.products.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_downloadauditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="digital_file",
            field=models.FileField(
                blank=True,
                storage=apps.products.storage.get_digital_file_storage,
                upload_to="products/digital/",
            ),
        ),
    ]
