# Generated by Django 5.1.15 on 2026-08-12 01:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_alter_product_digital_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("sale", "Venda"),
                            ("restock", "Reposição"),
                            ("cancel", "Cancelamento"),
                            ("return", "Devolução"),
                            ("adjustment", "Ajuste Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Positivo = entrada, Negativo = saída"
                    ),
                ),
                ("stock_before", models.PositiveIntegerField()),
                ("stock_after", models.PositiveIntegerField()),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Order #PED-123, Ajuste manual",
                        max_length=255,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=500)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_logs",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "-created_at"],
                        name="products_st_product_136c7e_idx",
                    ),
                    models.Index(
                        fields=["change_type"], name="products_st_change__86b8b3_idx"
                    ),
                ],
            },
        ),
    ]
