# Generated by Django 5.1.15 on 2026-08-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_alter_coupon_store_couponusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="affiliate_cookie_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Janela de cookie específica (dias). Vazio = usa a global.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="affiliate_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Produto disponível para o programa de afiliados",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="affiliate_terms",
            field=models.TextField(
                blank=True,
                help_text="Termos adicionais de afiliação definidos pelo vendedor",
            ),
        ),
    ]
