# Generated by Django 5.1.15 on 2026-08-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_product_affiliate_cookie_days_and_more"),
        ("stores", "0011_storefollower"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=0.0, max_digits=3
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sales_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_on_sale", "sales_count"],
                name="products_pr_is_on_s_813176_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured", "sales_count"],
                name="products_pr_is_feat_4335a7_idx",
            ),
        ),
    ]
